<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KGL5HQ6S" ignored="1" name="Test class02" tests="9" failures="2" timestamp="2020-05-28T20:59:02 EDT" time="64.486" errors="0">
  <testcase name="titleValidation" time="0.016" classname="com.class02.AssertionDemo"/>
  <testcase name="logoValidation" time="0.061" classname="com.class02.AssertionDemo"/>
  <testcase name="invalidLogin" time="1.521" classname="com.class02.NewTest">
    <failure type="java.lang.Exception">
      <![CDATA[java.lang.Exception
at com.class02.NewTest.invalidLogin(NewTest.java:103)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
  <testcase name="validLogin" time="0.0" classname="com.class02.NewTest">
    <skipped/>
  </testcase> <!-- validLogin -->
  <testcase name="logoAndWelcomeValidation" time="2.749" classname="com.class02.SoftAssertionDemo">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Logo is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Logo is not displayed expected [true] but found [false]
at com.class02.SoftAssertionDemo.logoAndWelcomeValidation(SoftAssertionDemo.java:46)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- logoAndWelcomeValidation -->
  <testcase name="fourthMethod" time="0.002" classname="com.class02.TaskOne"/>
  <testcase name="thirdMethod" time="0.002" classname="com.class02.TaskOne"/>
  <testcase name="secondMethod" time="0.002" classname="com.class02.TaskOne"/>
  <testcase name="firstMethod" time="0.001" classname="com.class02.TaskOne"/>
  <testcase name="firstMethod1" time="0.0" classname="com.class02.TaskOne">
    <ignored/>
  </testcase> <!-- firstMethod1 -->
</testsuite> <!-- Test class02 -->
